# Generated by Django 5.2.6 on 2025-09-16 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(max_length=50, unique=True, verbose_name='装置型号')),
                ('protection_structure', models.JSONField(verbose_name='保护结构与校验项')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_openid', models.IntegerField()),
                ('task_name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('original_image_url', models.ImageField(upload_to='media/')),
                ('ocr_result', models.CharField(max_length=500)),
                ('pts_file_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FaultParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protection_category', models.CharField(help_text='如‘线路保护’‘主变保护’', max_length=50, verbose_name='保护类别')),
                ('protection_item', models.CharField(help_text='如‘距离保护’‘差动保护’', max_length=50, verbose_name='具体保护项')),
                ('check_item', models.CharField(help_text='如‘单向接地’‘定值校验’', max_length=50, verbose_name='校验项')),
                ('fault_type', models.CharField(help_text='如‘A相接地’‘AB相间’', max_length=50, verbose_name='故障类型')),
                ('current_params', models.JSONField(help_text='如{"IA": "0.445∠-80°A"}', verbose_name='电流参数')),
                ('voltage_params', models.JSONField(help_text='如{"UA": "1.491∠0°V"}', verbose_name='电压参数')),
                ('time_params', models.JSONField(blank=True, null=True, verbose_name='时间参数')),
                ('formula', models.CharField(blank=True, help_text='如‘动作电流=1.2×额定电流’', max_length=200, null=True, verbose_name='计算公式')),
                ('device_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_params', to='jibao.devicetemplate', verbose_name='关联装置模板')),
            ],
        ),
    ]
