# Generated by Django 5.2.6 on 2025-09-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jibao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetemplate',
            name='manufacture',
            field=models.CharField(default='南瑞继保', max_length=50, verbose_name='生产厂家'),
            preserve_default=False,
        ),
    ]
