# Generated by Django 5.2.6 on 2025-09-16 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jibao', '0002_devicetemplate_manufacture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='original_image_url',
        ),
        migrations.RemoveField(
            model_name='task',
            name='pts_file_url',
        ),
        migrations.AddField(
            model_name='task',
            name='pts_file',
            field=models.FileField(blank=True, null=True, upload_to='pts_files/%Y%m%d/', verbose_name='生成的PTS文件'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='processing', max_length=20, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ocr_result',
            field=models.JSONField(blank=True, null=True, verbose_name='合并后的OCR识别结果'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=100, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_openid',
            field=models.CharField(max_length=100, verbose_name='用户OpenID'),
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='original_images/%Y%m%d/', verbose_name='定值单图片')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('ocr_status', models.CharField(choices=[('pending', '待识别'), ('success', '识别成功'), ('failed', '识别失败')], default='pending', max_length=20, verbose_name='单图OCR状态')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jibao.task', verbose_name='关联任务')),
            ],
        ),
    ]
