# Generated by Django 5.2.6 on 2025-09-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jibao', '0003_remove_task_original_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='device_model',
            field=models.CharField(blank=True, choices=[], max_length=20, null=True, verbose_name='装置型号'),
        ),
    ]
