# Generated by Django 5.2.6 on 2025-09-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jibao', '0004_task_device_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fault_type',
            field=models.CharField(blank=True, choices=[], max_length=20, null=True, verbose_name='故障类型'),
        ),
        migrations.AddField(
            model_name='task',
            name='protect_type',
            field=models.CharField(blank=True, choices=[], max_length=20, null=True, verbose_name='保护类型'),
        ),
        migrations.AddField(
            model_name='task',
            name='sub_fault_type',
            field=models.CharField(blank=True, choices=[], max_length=20, null=True, verbose_name='细分故障类型'),
        ),
    ]
