# Generated by Django 5.2.6 on 2025-09-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jibao', '0005_task_fault_type_task_protect_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='fault_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='protect_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sub_fault_type',
        ),
        migrations.AddField(
            model_name='devicetemplate',
            name='params',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='定值参数'),
        ),
    ]
