# Generated by Django 5.2.6 on 2025-09-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jibao', '0006_remove_task_fault_type_remove_task_protect_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetemplate',
            name='params',
            field=models.JSONField(blank=True, null=True, verbose_name='定值参数'),
        ),
    ]
