# Generated by Django 5.2.6 on 2025-10-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jibao', '0007_alter_devicetemplate_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetemplate',
            name='device_type',
            field=models.CharField(choices=[('line', '线路保护'), ('transform', '主变保护'), ('busbar', '母差保护')], default='line', max_length=50, verbose_name='装置类型'),
        ),
    ]
