# Generated by Django 5.2.6 on 2025-10-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jibao', '0008_devicetemplate_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protect_type', models.CharField(choices=[('line', '线路保护'), ('transform', '主变保护'), ('busbar', '母差保护')], default='line', max_length=50, verbose_name='保护类型')),
                ('protection_structure', models.JSONField(verbose_name='保护及其参数')),
            ],
        ),
        migrations.DeleteModel(
            name='FaultParameter',
        ),
    ]
