# Generated by Django 5.2.6 on 2025-10-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jibao', '0009_protecttemplate_delete_faultparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protecttemplate',
            name='protect_type',
            field=models.CharField(choices=[('line', '线路保护'), ('line_10', '10kv线路保护'), ('transform', '主变保护'), ('busbar', '母差保护')], default='line', max_length=50, verbose_name='保护类型'),
        ),
    ]
